# Generated by Django 3.0.5 on 2020-04-03 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b2b_app', '0002_query'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='contactEmail',
        ),
        migrations.AddField(
            model_name='company',
            name='contactNumber',
            field=models.CharField(default=1, max_length=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='searchSites',
            field=models.CharField(choices=[('Test Bookstore', 'Test Bookstore'), ('Google Books', 'Google Books'), ('Kobo', 'Kobo'), ('Livraria Cultura', 'Livraria Cultura'), ('Scribd', 'Scribd')], default='Test Bookstore', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='isContact',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='None', max_length=150),
            preserve_default=False,
        ),
    ]
