# Generated by Django 3.0.5 on 2020-04-03 18:35

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('b2b_app', '0003_auto_20200403_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='bookFormats',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('EBook', 'EBook'), ('Audio Book', 'Audio Book'), ('Print Book', 'Print Book')], default='EBook', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='company',
            name='searchSites',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Test Bookstore', 'Test Bookstore'), ('Google Books', 'Google Books'), ('Kobo', 'Kobo'), ('Livraria Cultura', 'Livraria Cultura'), ('Scribd', 'Scribd')], max_length=100),
        ),
    ]
