# Generated by Django 3.0.5 on 2020-04-03 18:47

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('b2b_app', '0004_auto_20200403_1335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='isContact',
        ),
        migrations.AddField(
            model_name='company',
            name='contactPerson',
            field=models.CharField(default='Tyler Mathews', max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='company',
            name='searchSites',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('TB', 'Test Bookstore'), ('GB', 'Google Books'), ('KB', 'Kobo'), ('LC', 'Livraria Cultura'), ('SD', 'Scribd')], max_length=100),
        ),
    ]
