# Generated by Django 3.0.5 on 2020-04-03 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('b2b_app', '0005_auto_20200403_1347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='queries',
        ),
    ]
