# Generated by Django 3.0.5 on 2020-04-07 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('b2b_app', '0006_remove_user_queries'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Query',
        ),
    ]
