# Generated by Django 3.0.5 on 2020-04-07 20:44

from django.db import migrations
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('b2b_app', '0007_delete_query'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='queries',
            field=picklefield.fields.PickledObjectField(default={'Tyler Mathews': '4/7/2020'}, editable=False),
            preserve_default=False,
        ),
    ]
