# Generated by Django 3.0.5 on 2020-04-15 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('b2b_app', '0009_auto_20200407_1601'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='bookFormats',
            new_name='book_formats',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='contactNumber',
            new_name='contact_number',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='contactPerson',
            new_name='contact_person',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='searchSites',
            new_name='search_sites',
        ),
    ]
